# Generated by Django 3.2.7 on 2021-09-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('biography', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mbtiType', models.CharField(max_length=10)),
                ('enneagram', models.CharField(max_length=10)),
            ],
        ),
    ]
