# Generated by Django 3.2.7 on 2021-10-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211003_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('KR', 'KOREAN'), ('JP', 'JAPANESE')], default='EN', max_length=3),
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
            preserve_default=False,
        ),
    ]
